server:      # noinspection SpellCheckingInspection
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8081/realms/nome-criativo}
      client:
        registration:
          keycloak-client:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID:bff-client}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:THbK5qmCEIWl93PjhVRNZkJlP79PQ5Lv}
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: ${KEYCLOAK_TOKEN_URI:http://localhost:8081/realms/nome-criativo/protocol/openid-connect/token}
